tuqulore/vue-3-practices

LEARNING_MATERIAL.md
用意済みの演習については直接演習環境にアクセス出来るようリンクに差し替える
=> docs: 演習リンクの追加

.github/workflows/gh-pages.yaml
docsディレクトリ下に変化がある場合のみスライドのビルドをするように
=> chore: ワークフローのトリガー抑制

practice-reactive-class-binding-event-handling/src/App.vue
学習資料を上から学習した際に、Composition APIの利用方法をまだ学んでいないにもかかわらず知っている必要がある状態だったため
https://github.com/tuqulore/vue-3-practices/blob/main/LEARNING_MATERIAL.md#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%83%8F%E3%83%B3%E3%83%89%E3%83%AA%E3%83%B3%E3%82%B0
=> feat: リアクティブな参照に対する値の代入方法を知らなくても問題ないように

sample-fetch-router/src/App.vue, sample-fetch-router/src/components/PostDetail.vue, sample-fetch-router/src/components/PostList.vue, sample-fetch-router/src/main.js, sample-grid-component/src/App.vue, sample-grid-component/src/components/DemoGrid.vue, sample-markdown-editor/src/App.vue
=> docs: サンプルアプリのコードコメント

LEARNING_MATERIAL.md
=> docs: キーポイントの整理

LEARNING_MATERIAL.md
=> docs: 学習資料にスタイルガイドを追加

docs/components/ReactiveSample.vue, docs/components/TwoWayBindingSample.vue, docs/slides.md
- 算出プロパティとウォッチャを前にもってくるように（→テンプレート構文→コンポーネントの流れにしたいため）
- 喋ることを思い出せるような見出しの追加など
- 使用するテーマによってはinputの色のコントラストがよくないことへの対応
=> docs: はじめに、リアクティブの探求、算出プロパティ、ウォッチャの推敲

handson-nuxt-playground/nuxt.config.js, handson-nuxt-playground/package.json, handson-nuxt/nuxt.config.js, handson-nuxt/package.json, yarn.lock
=> fix: nuxt3が動作しない

docs/components/TwowayChild.vue, docs/slides.md
=> docs: 双方向バインディング

sample-fetch-router/src/App.vue, sample-fetch-router/src/components/PostDetail.vue, sample-fetch-router/src/components/PostList.vue, sample-fetch-router/src/main.js
- ドキュメントのurlの更新
- Same Origin Policy で画像が表示されないことへの対応
- コードの整形
=> feat: fetch-router サンプルの更新

docs/slides.md
=> docs: コードの省略の解消

docs/slides.md
=> docs: 課題の説明

docs/slides.md
=> docs: Vue 3 と Nuxt 3 の比較の説明

docs/slides.md
=> docs: 課題のハンズオン環境の差し替え

docs/slides.md
=> docs: 添字によるリストレンダリングの説明

docs/package.json, yarn.lock
shiki 0.12.1 に起因する現象
slidev を 0.38.1 に戻すことで対処
ref https://github.com/slidevjs/slidev/issues/799
=> fix: コードブロックが重複して表示される

docs/components/CounterSample.vue, docs/components/EmitChild.vue, docs/components/EmitParent.vue, docs/components/FirstSample.vue, docs/components/ReactiveSample.vue, docs/components/TwoWayBindingSample.vue, docs/components/TwowayChild.vue, docs/components/TwowayParent.vue, docs/slides.md
=> feat: スライドの script setup 対応

handson-fetch-router-nuxt-finish/nuxt.config.js, handson-nuxt-playground/nuxt.config.js, handson-nuxt/nuxt.config.js
=> fix: (0 , _nuxt.defineNuxtConfig) is not a function

yarn.lock
=> fix: Cannot find module '@nuxt/vite-builder'

handson-fetch-router-nuxt-finish/README.md, handson-nuxt-playground/README.md, handson-nuxt/README.md
https://github.com/nuxt/starter/blob/v3-stackblitz/README.md への追従
=> docs: Nuxt 環境の README

handson-fetch-router-nuxt-finish/pages/index.vue, handson-fetch-router-nuxt-finish/pages/posts/[id].vue
=> chore(handson-fetch-router-nuxt): use script setup

docs/slides.md
resolve #238 
説明のリライト、コードサンプルでトラブルを予防できる箇所の更新等の変更、VueUseの説明の追加を含みます
=> docs: Nuxt 3 の説明の更新、etc.

README.md
=> docs: Nuxt 3 版デザインラボビューアーが動作しない件

docs/slides.md
=> docs: スライドの Nuxt 3 公式ドキュメント URL の更新

LEARNING_MATERIAL.md
=> docs: 補助資料の公式ドキュメントの URL の更新

.codesandbox/tasks.json, README.md, tasks.js
次の URL から動作が確認できます https://codesandbox.io/p/github/tuqulore/vue-3-practices/support-codesandbox-project?file=%2FREADME.md
=> chore: Support CodeSandBox Projects

.codesandbox/tasks.json, tasks.js
スライドをCodeSandbox Projectsで表示するためのタスクを追加する変更です
=> chore(CodeSandbox Projects): setup slide task

docs/slides.md
=> docs: Nuxt 3 関連のハンズオンの手順の更新

.github/release.yaml, renovate.json
=> chore: 自動生成リリースノートのセットアップ

docs/slides.md
resolve #262
関連 #280 
Nuxtのハンズオンの流れとして、名前付きレイアウトを用意して、特定のページで切り替えるように準備します。
=> docs: レイアウトの切り替えには definePageMeta を使う

.github/workflows/format.yaml, package.json
=> chore: setup format ci

.github/workflows/gh-pages.yaml
=> chore: PRでスライド編集時GitHub Pagesにデプロイしない

README.md
https://developer.stackblitz.com/docs/platform/browser-support/ に記載のある内容に合わせて
サポート状況を更新します
=> docs: StackBlitzのサポート状況の更新

docs/slides.md
=> docs: ローカル環境でのアプリの起動、コードの閲覧編集の手順

docs/slides.md
=> docs: drop console.log from watch sample

docs/components/CounterSample.vue, docs/components/EmitChild.vue, docs/components/EmitParent.vue, docs/components/FirstSample.vue, docs/components/TwoWayBindingSample.vue, docs/components/TwowayChild.vue, docs/components/TwowayParent.vue, docs/slides.md
=> docs: SFCの記述を<script>先頭にする

handson-fetch-router-finish/src/components/PostDetail.vue, handson-fetch-router-nuxt-finish/pages/posts/[id].vue, handson-fetch-router/src/components/PostDetail.vue, handson-fetch-router/src/main.js, practice-computed-answer/src/App.vue, practice-emit-event-handling-answer/src/components/TestButton.vue, practice-mounted-answer/src/App.vue, practice-mustache-setup-answer/src/App.vue, practice-reactive-class-binding-event-handling-answer/src/App.vue, practice-reactive-props-component-v-model-answer-1/src/App.vue, practice-reactive-props-component-v-model-answer-2/src/App.vue, practice-reactive-props-component-v-model-answer-2/src/components/MessageIndicator.vue, practice-reactive-props-component-v-model-answer-3/src/App.vue, practice-reactive-props-component-v-model-answer-3/src/components/MessageIndicator.vue, practice-scoped-css-component-answer/src/App.vue, practice-slot-answer/src/components/Component1.vue, practice-v-for-answer/src/App.vue, practice-v-if-answer/src/App.vue, practice-v-model-answer/src/App.vue, practice-vue-router-answer-1/src/main.js, practice-vue-router-answer-2/src/main.js
=> docs: v3.ja.vuejs.org → ja.vuejs.org

handson-fetch-router-nuxt-finish/README.md, handson-fetch-router-nuxt-finish/nuxt.config.js, handson-fetch-router-nuxt-finish/pages/index.vue, handson-fetch-router-nuxt-finish/tsconfig.json, handson-nuxt-playground/README.md, handson-nuxt-playground/nuxt.config.js, handson-nuxt-playground/tsconfig.json, handson-nuxt/README.md, handson-nuxt/nuxt.config.js, handson-nuxt/tsconfig.json
=> docs: v3.nuxtjs.org → nuxt.com

docs/slides.md
=> docs: ハイライトや矢印のずれを直す

handson-grid-component/src/components/DemoGrid.vue
=> feat(handson-grid-component): コードの更新

docs/slides.md
resolve https://github.com/tuqulore/vue-3-practices/issues/255
=> docs: Nuxt 3 の特徴や使うとうれしいことを書き下す

README.md, docs/slides.md, handson-sticky/.gitignore, handson-sticky/README.md, handson-sticky/app.vue, handson-sticky/components/Sticky.vue, handson-sticky/composables/useStickies.js, handson-sticky/nuxt.config.js, handson-sticky/package.json, handson-sticky/pages/index.vue, handson-sticky/pages/sub.vue, handson-sticky/tsconfig.json
https://stackblitz.com/edit/nuxt-starter-eqvxvb の移植
resolve #296
動作確認 https://stackblitz.com/fork/github/tuqulore/vue-3-practices/tree/feat-handson-sticky/handson-sticky?file=src/App.vue&terminal=dev
=> feat: 付箋アプリ

handson-fetch-router-nuxt-finish/nuxt.config.js, handson-nuxt-playground/nuxt.config.js, handson-nuxt/nuxt.config.js
ref https://github.com/tuqulore/vue-3-practices/issues/379#issuecomment-1862155331
正しくないモジュールからインポートしていることが原因
=> fix: defineNuxtConfig is not a function

docs/README.md
関連 https://github.com/tuqulore/vue-3-practices/issues/621#issuecomment-2404170512
=> feat: 手元起動のためのREADME.mdを追加

docs/slides.md
closes https://github.com/tuqulore/vue-3-practices/issues/407
=> feat: defineModelの説明

docs/slides.md
- 算出プロパティ→算出関数
- 書き込める算出プロパティは取り扱わない（defineModelでカバーできる）
- サンプルコードの省スペース化
=> リアクティブに関する推敲

docs/components/FirstSample.vue, docs/slides.md
他のどこにも SFC 構文の説明をしている場所がないため
ついでに mustache 構文も説明して最低限の試し書きがしやすいようにします
=> 最初のサンプルで SFC の説明をする

docs/slides.md
=> 書いて試せるようPlaygroundのリンクをつける & 公式 Doc リンクは興味がある人向けにする

docs/slides.md
=> 動作しないサンプルコードの修正

docs/slides.md
https://github.com/tuqulore/vue-3-practices/pull/662#discussion_r1877040941 の revert 漏れ
=> 算出関数 → 算出プロパティ

handson-fetch-router-finish/src/components/PostDetail.vue, handson-fetch-router-finish/src/main.js, handson-fetch-router-nuxt-finish/pages/posts/[id].vue, handson-fetch-router/src/components/PostDetail.vue
- テンプレート参照の説明
- crossorigin 属性の説明
=> *-fetch-router-* にいくつかコメントを追加する

docs/slides.md
=> Vue コンポーネントはファイルとしては .vue ファイルで構成される

.github/workflows/lint.yaml, .vscode/settings.json, handson-fetch-router-nuxt-finish/eslint.config.mjs, handson-fetch-router-nuxt-finish/nuxt.config.js, handson-fetch-router-nuxt-finish/package.json, handson-nuxt-playground/eslint.config.mjs, handson-nuxt-playground/nuxt.config.js, handson-nuxt-playground/package.json, handson-nuxt/eslint.config.mjs, handson-nuxt/nuxt.config.js, handson-nuxt/package.json, handson-sticky/eslint.config.mjs, handson-sticky/nuxt.config.js, handson-sticky/package.json, package.json, practice-slot-answer/src/App.vue, yarn.lock
https://eslint.nuxt.com/packages/module にしたがって設定します
resolve #656 , resolve #385
=> Nuxt ESLint Module のセットアップ

docs/components/ReactiveSample.vue, docs/slides.md
resolve #668 
おもにユーティリティクラスを指定してダークモードの想定が漏れているところにdrakバリアントを追加するなどしています
=> ダークモードでのコントラストが悪いところを調整する

package.json, yarn.lock
=> yarn-deduplicate によるパッケージ依存関係の整理
